# Lung Cancer Prediction

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [3]:
data = pd.read_csv(r".\Datasets\survey_lung_cancer.csv")
data.head(3)

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0    MALE   69        0               1        1              0   
1    MALE   74        1               0        0              0   
2  FEMALE   59        0               0        0              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                0         1         0         1                  1         1   
1                1         1         1         0                  0         0   
2                0         1         0         1                  0         1   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN LUNG_CANCER  
0                    1                      1           1         YES  
1                    1                      1           1         YES  
2                    1                      0           1          NO

In [4]:
data.shape

(309, 16)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   GENDER                 309 non-null    object
 1   AGE                    309 non-null    int64 
 2   SMOKING                309 non-null    int64 
 3   YELLOW_FINGERS         309 non-null    int64 
 4   ANXIETY                309 non-null    int64 
 5   PEER_PRESSURE          309 non-null    int64 
 6   CHRONIC DISEASE        309 non-null    int64 
 7   FATIGUE                309 non-null    int64 
 8   ALLERGY                309 non-null    int64 
 9   WHEEZING               309 non-null    int64 
 10  ALCOHOL CONSUMING      309 non-null    int64 
 11  COUGHING               309 non-null    int64 
 12  SHORTNESS OF BREATH    309 non-null    int64 
 13  SWALLOWING DIFFICULTY  309 non-null    int64 
 14  CHEST PAIN             309 non-null    int64 
 15  LUNG_CANCER            

In [6]:
data.describe()

AGE     SMOKING  YELLOW_FINGERS     ANXIETY  PEER_PRESSURE  \
count  309.000000  309.000000      309.000000  309.000000     309.000000   
mean    62.673139    0.563107        0.569579    0.498382       0.501618   
std      8.210301    0.496806        0.495938    0.500808       0.500808   
min     21.000000    0.000000        0.000000    0.000000       0.000000   
25%     57.000000    0.000000        0.000000    0.000000       0.000000   
50%     62.000000    1.000000        1.000000    0.000000       1.000000   
75%     69.000000    1.000000        1.000000    1.000000       1.000000   
max     87.000000    1.000000        1.000000    1.000000       1.000000   

       CHRONIC DISEASE    FATIGUE     ALLERGY     WHEEZING  ALCOHOL CONSUMING  \
count       309.000000  309.000000  309.000000  309.000000         309.000000   
mean          0.504854    0.673139    0.556634    0.556634           0.556634   
std           0.500787    0.469827    0.497588    0.497588           0.497588   
min           0.000000    0.000000    0.000000    0.000000           0.000000   
25%           0.000000    0.000000    0.000000    0.000000           0.000000   
50%           1.000000    1.000000    1.000000    1.000000           1.000000   
75%           1.000000    1.000000    1.000000    1.000000           1.000000   
max           1.000000    1.000000    1.000000    1.000000           1.000000   

         COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  
count  309.000000           309.000000             309.000000  309.000000  
mean     0.579288             0.640777               0.469256    0.556634  
std      0.494474             0.480551               0.499863    0.497588  
min      0.000000             0.000000               0.000000    0.000000  
25%      0.000000             0.000000               0.000000    0.000000  
50%      1.000000             1.000000               0.000000    1.000000  
75%      1.000000             1.000000               1.000000    1.000000  
max      1.000000             1.000000               1.000000    1.000000

In [7]:
data.isnull().sum()

GENDER                   0
AGE                      0
SMOKING                  0
YELLOW_FINGERS           0
ANXIETY                  0
PEER_PRESSURE            0
CHRONIC DISEASE          0
FATIGUE                  0
ALLERGY                  0
WHEEZING                 0
ALCOHOL CONSUMING        0
COUGHING                 0
SHORTNESS OF BREATH      0
SWALLOWING DIFFICULTY    0
CHEST PAIN               0
LUNG_CANCER              0
dtype: int64

## Label Encoder

In [8]:
label_encoder = LabelEncoder()
data['GENDER'] = label_encoder.fit_transform(data['GENDER'])
data['GENDER'].unique()

array([1, 0])

In [9]:
data['LUNG_CANCER'] = label_encoder.fit_transform(data['LUNG_CANCER'])
data['LUNG_CANCER'].unique()

array([1, 0])

In [10]:
data.head(3)

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0       1   69        0               1        1              0   
1       1   74        1               0        0              0   
2       0   59        0               0        0              1   

   CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  \
0                0         1         0         1                  1         1   
1                1         1         1         0                  0         0   
2                0         1         0         1                  0         1   

   SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  LUNG_CANCER  
0                    1                      1           1            1  
1                    1                      1           1            1  
2                    1                      0           1            0

In [11]:
# checking the distribution of target variable
data['LUNG_CANCER'].value_counts()

LUNG_CANCER
1    270
0     39
Name: count, dtype: int64

### 1 ---> Defective Lung
### 0 ---> Healthy Lung

In [12]:
data.to_csv(".\Datasets\preprocessed_lungs_data.csv",index=False)

### Splitting the features & target

In [13]:
x = data.iloc[:,:-1]
y = data['LUNG_CANCER']

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

## Model Training

In [20]:
model = LogisticRegression()

In [21]:
model.fit(x_train,y_train)

C:\Users\lenovo\Desktop\Coding\PYTHON\Edunet Internship\medical_diagnosis\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

## Model Evaluation

In [22]:
# accuracy on training data
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction,y_train)
print("Accuracy on Training data :",training_data_accuracy)

Accuracy on Training data : 0.9352226720647774


In [23]:
# accuracy on testing data
x_test_prediction = model.predict(x_test)
testing_data_accuracy = accuracy_score(x_test_prediction,y_test)
print("Accuracy on Testing data :",testing_data_accuracy)

Accuracy on Testing data : 0.9193548387096774


## Predictive model

In [24]:
input_data = (0,61,1,1,1,1,2,2,1,1,1,1,2,1,1)

# change the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array as we are predicting for only on instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if(prediction[0] == 0):
    print("The Person does not have a lung cancer")
else:
    print("The Person has lung cancer")

[1]
The Person has lung cancer


C:\Users\lenovo\Desktop\Coding\PYTHON\Edunet Internship\medical_diagnosis\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


## Saving the trained model

In [25]:
import pickle

In [26]:
filename = ".\Models\lungs_disease_model.sav"
pickle.dump(model,open(filename,"wb"))

In [27]:
# loading the saved model
loaded_model = pickle.load(open(".\Models\lungs_disease_model.sav","rb"))

In [28]:
loaded_model.predict(input_data_reshaped)

C:\Users\lenovo\Desktop\Coding\PYTHON\Edunet Internship\medical_diagnosis\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])